name: manual
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  gh:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/pheobeyeung/PolyScopeX-SDK/codespaces \
             -f "ref=testing" -f "machine=standardLinux32gb"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}

